spring.application.name=backend-spring
server.port=8080

spring.data.mongodb.uri=mongodb+srv://metinakifzehir55_db_user:GCiQQ9WIEvdUhADd@cluster0.6uy3reg.mongodb.net/restaurantsdb?retryWrites=true&w=majority